version: '3.4'

services:
  db:
    container_name: DB_finance_trackr
    image: mariadb:latest
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: DB_pets
      MYSQL_USER: root
      MYSQL_PASSWORD: ""

  petsnode:
    image: petsnode
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db
      
networks:
  petsnode:
